version: "3.9"

services:
  app:
    container_name: home_monitor_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3020:3000"
    env_file:
      - .env
    networks:
      - home-monitor-net
    restart: unless-stopped

networks:
  home-monitor-net:
    external: true
